version: '3.7'

services:
    crypto-service-bus-queue-host:
        container_name: "crypto_service_bus_queue_host"
        build:
            context: ./
            dockerfile: Crypto.HostedServices.ServiceBusQueueHost/Dockerfile
        image: "rhe89/hub-crypto-service-bus-queue-host"

    crypto-scheduled-host:
        container_name: "crypto_scheduled_host"
        build:
            context: ./
            dockerfile: Crypto.HostedServices.ScheduledHost/Dockerfile
        image: "rhe89/hub-crypto-scheduled-host"

    crypto-api:
        container_name: "crypto_api"
        build: 
            context: ./
            dockerfile: Crypto.Web.Api/Dockerfile
        image: "rhe89/hub-crypto-api"